name: Build Binaries

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            artifact_name: binary
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: binary.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: binary

    steps:
    - uses: actions/checkout@v2
    
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}
        
    - run: cargo build --release --target ${{ matrix.target }}
    
    - name: Build Assets
      run: |
        cargo build --release --target ${{ matrix.target }}
        tar -C target/${{ matrix.target }}/release/ -czvf binary-${{ matrix.target }}.tar.gz binary${{ runner.os == 'Windows' && '.exe' || '' }}
    - name: Upload Release Assets
      if: ${{ github.event_name != 'workflow_dispatch' }}
      uses: softprops/action-gh-release@v1
      with:
        files: '*.tar.gz'
